// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "appointment-api/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// WorkingHourRepository is an autogenerated mock type for the WorkingHourRepository type
type WorkingHourRepository struct {
	mock.Mock
}

type WorkingHourRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkingHourRepository) EXPECT() *WorkingHourRepository_Expecter {
	return &WorkingHourRepository_Expecter{mock: &_m.Mock}
}

// GetWorkingHourByUserID provides a mock function with given fields: ctx, userID
func (_m *WorkingHourRepository) GetWorkingHourByUserID(ctx context.Context, userID int64) ([]entity.WorkingHour, error) {
	ret := _m.Called(ctx, userID)

	var r0 []entity.WorkingHour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.WorkingHour, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.WorkingHour); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.WorkingHour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkingHourRepository_GetWorkingHourByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkingHourByUserID'
type WorkingHourRepository_GetWorkingHourByUserID_Call struct {
	*mock.Call
}

// GetWorkingHourByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *WorkingHourRepository_Expecter) GetWorkingHourByUserID(ctx interface{}, userID interface{}) *WorkingHourRepository_GetWorkingHourByUserID_Call {
	return &WorkingHourRepository_GetWorkingHourByUserID_Call{Call: _e.mock.On("GetWorkingHourByUserID", ctx, userID)}
}

func (_c *WorkingHourRepository_GetWorkingHourByUserID_Call) Run(run func(ctx context.Context, userID int64)) *WorkingHourRepository_GetWorkingHourByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *WorkingHourRepository_GetWorkingHourByUserID_Call) Return(_a0 []entity.WorkingHour, _a1 error) *WorkingHourRepository_GetWorkingHourByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkingHourRepository_GetWorkingHourByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]entity.WorkingHour, error)) *WorkingHourRepository_GetWorkingHourByUserID_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewWorkingHourRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkingHourRepository creates a new instance of WorkingHourRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkingHourRepository(t mockConstructorTestingTNewWorkingHourRepository) *WorkingHourRepository {
	mock := &WorkingHourRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
